-m

diff --git a/scripts/notify b/scripts/notify
--- a/scripts/notify
+++ b/scripts/notify
@@ -11,7 +11,8 @@ Options:
   -h, --help                Display this message and exit
   -l, --list-backends       Lists all supported backends, such as 'libnotify'  
   -b, --backend <backend>   Specify the backend to use (from the list of supported ones)
-  -i, --icon <icon>         Icon to show in the notification (<icon> can be a path, name etc.)
+  -i, --icon <file>         Icon to show in the notification (<file> can be a path, name etc.)
+  -a, --audio <file>        Audio clip to play with the notification (<file> can be a path, name etc.)
 
 Examples:
   notify 'Hello' 'World!'
@@ -39,10 +40,15 @@ assign_parameter_value() {
     backend=$1
   elif [ "$icon" == "-1" ]; then
     icon=$1
+  elif [ "$audio" == "-1" ]; then
+    audio=$1
   elif ! [ -n "$title" ]; then
-    title=$1
-  elif ! [ -n "$description" ]; then
-    description=$1
+    title="$1"
+  else
+    if [ -n "$description" ]; then
+      description="$description"
+    fi
+    description="$1"
   fi
 }
 
@@ -56,18 +62,20 @@ validate_parameters() {
   fi
 
   if [ "$icon" == "-1" ]; then
-    error "Missing <icon> required by the '-i/--icon' flag."
+    error "Missing <file> required by the '-i/--icon' flag."
+  fi
+
+  if [ "$audio" == "-1" ]; then
+    error "Missing <file> required by the '-a/--audio' flag."
   fi
 }
 
 send_libnotify() {
-  action="notify-send $1 $2"
+  action="notify-send \"$1\" \"$2\""
 
   if [ -n "$icon" ]; then
     action="$action -i $icon"
   fi
-
-  exec $action
 }
 
 send_notification() {
@@ -78,7 +86,7 @@ send_notification() {
         echo "Try 'notify --list-backends' for the list of supported backends."
         exit 1
       fi
-      send_libnotify $1 $2
+      send_libnotify "$1" "$2"
     ;;
     *)
       echo "[FATAL] notify: Backend '$1' not supported."
@@ -86,6 +94,23 @@ send_notification() {
       exit 1
     ;;
   esac
+
+  if [ -n "$audio" ]; then
+    if [ -x "$(command -v paplay)" ]; then
+      play_audio="paplay $audio"
+    elif [ -x "$(command -v aplay)" ]; then
+      play_audio="aplay $audio"
+    fi
+
+    if ! [ -n "$play_audio" ]; then
+      echo "[WARN] notify: Could not detect either ALSA or PluseAudio for playing sounds."
+      exit 1
+    fi
+
+    action="$action && $play_audio"
+  fi
+
+  exec sh -c "$action"
 }
 
 main() {
@@ -115,6 +140,9 @@ main() {
       -i | --icon)
         icon=-1
       ;;
+      -a | --audio)
+        audio=-1
+      ;;
       -*)
         cat <<EOF
 [ERROR] notify: invalid option -- '$i'
@@ -123,13 +151,13 @@ EOF
         exit 1
       ;;
       *)
-        assign_parameter_value $i
+        assign_parameter_value "$i"
       ;;
     esac
   done
 
   validate_parameters
-  send_notification $title $description
+  send_notification "$title" "$description"
 
   exit 0
 }
